/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

/**
 *
 * @author Marcos Assumpcao, Ubirajara Oliveira, Vinicius Souza
 */
public class TelaInicio extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicio
     */
    public TelaInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu7 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jDesktop = new javax.swing.JDesktopPane();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        javax.swing.JMenuItem jMenuItemCadFuncionario = new javax.swing.JMenuItem();
        jMenuItemCadCliente = new javax.swing.JMenuItem();
        javax.swing.JMenuItem jMenuItemCadGerente = new javax.swing.JMenuItem();
        jMenuItemCadChamado = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemConsultaFuncionario = new javax.swing.JMenuItem();
        jMenuItemConsultaCliente = new javax.swing.JMenuItem();
        jMenuItemConsultaGerente = new javax.swing.JMenuItem();
        jMenuItemConsultaChamado = new javax.swing.JMenuItem();

        jMenu7.setText("jMenu7");

        jMenuItem7.setText("jMenuItem7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktop.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jDesktopLayout = new javax.swing.GroupLayout(jDesktop);
        jDesktop.setLayout(jDesktopLayout);
        jDesktopLayout.setHorizontalGroup(
            jDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1277, Short.MAX_VALUE)
        );
        jDesktopLayout.setVerticalGroup(
            jDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 624, Short.MAX_VALUE)
        );

        jMenuBar2.setToolTipText("Sistema HelpDesk");

        jMenu4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vinicius\\Desktop\\usercard_01 (1).png")); // NOI18N
        jMenu4.setText("Cadastro");

        jMenuItemCadFuncionario.setText("Funcionario");
        jMenuItemCadFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadFuncionarioActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemCadFuncionario);

        jMenuItemCadCliente.setText("Cliente");
        jMenuItemCadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadClienteActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemCadCliente);

        jMenuItemCadGerente.setText("Gerente");
        jMenuItemCadGerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadGerenteActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemCadGerente);

        jMenuItemCadChamado.setText("Chamado");
        jMenuItemCadChamado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadChamadoActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemCadChamado);

        jMenuBar2.add(jMenu4);

        jMenu1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vinicius\\Desktop\\25_folder.png")); // NOI18N
        jMenu1.setText("Consulta");

        jMenuItemConsultaFuncionario.setText("Funcionario");
        jMenuItemConsultaFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultaFuncionarioActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemConsultaFuncionario);

        jMenuItemConsultaCliente.setText("Cliente");
        jMenuItemConsultaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultaClienteActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemConsultaCliente);

        jMenuItemConsultaGerente.setText("Gerente");
        jMenuItemConsultaGerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultaGerenteActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemConsultaGerente);

        jMenuItemConsultaChamado.setText("Chamado");
        jMenu1.add(jMenuItemConsultaChamado);

        jMenuBar2.add(jMenu1);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktop, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCadFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadFuncionarioActionPerformed
        // TODO add your handling code here:
        CadFuncionario cadFuncionario = new CadFuncionario();
        cadFuncionario.setVisible(true);
        jDesktop.add(cadFuncionario);
    }//GEN-LAST:event_jMenuItemCadFuncionarioActionPerformed

    private void jMenuItemCadGerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadGerenteActionPerformed
        // TODO add your handling code here:
        CadGerente cadGerente = new CadGerente();
        cadGerente.setVisible(true);
        jDesktop.add(cadGerente);
    }//GEN-LAST:event_jMenuItemCadGerenteActionPerformed

    private void jMenuItemConsultaFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultaFuncionarioActionPerformed
        // TODO add your handling code here:
        ConsultaFuncionario ConsultaFuncionario = new ConsultaFuncionario();
        ConsultaFuncionario.setVisible(true);
        jDesktop.add(ConsultaFuncionario);
    }//GEN-LAST:event_jMenuItemConsultaFuncionarioActionPerformed

    private void jMenuItemCadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadClienteActionPerformed
        // TODO add your handling code here:
        CadCliente cadCliente = new CadCliente();
        cadCliente.setVisible(true);
        jDesktop.add(cadCliente);
    }//GEN-LAST:event_jMenuItemCadClienteActionPerformed

    private void jMenuItemCadChamadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadChamadoActionPerformed
        // TODO add your handling code here:
        CadChamado cadChamado = new CadChamado();
        cadChamado.setVisible(true);
        jDesktop.add(cadChamado);
    }//GEN-LAST:event_jMenuItemCadChamadoActionPerformed

    private void jMenuItemConsultaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultaClienteActionPerformed
        // TODO add your handling code here:
        ConsultaCliente ConsultaCliente = new ConsultaCliente();
        ConsultaCliente.setVisible(true);
        jDesktop.add(ConsultaCliente);
    }//GEN-LAST:event_jMenuItemConsultaClienteActionPerformed

    private void jMenuItemConsultaGerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultaGerenteActionPerformed
        // TODO add your handling code here:
        ConsultaGerente ConsultaGerente = new ConsultaGerente();
        ConsultaGerente.setVisible(true);
        jDesktop.add(ConsultaGerente);
    }//GEN-LAST:event_jMenuItemConsultaGerenteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicio().setVisible(true);
            }
        });
    }  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktop;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItemCadChamado;
    private javax.swing.JMenuItem jMenuItemCadCliente;
    private javax.swing.JMenuItem jMenuItemConsultaChamado;
    private javax.swing.JMenuItem jMenuItemConsultaCliente;
    private javax.swing.JMenuItem jMenuItemConsultaFuncionario;
    private javax.swing.JMenuItem jMenuItemConsultaGerente;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    // End of variables declaration//GEN-END:variables
}
